---
title: "Final project documentation - PDA"
output:
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
    css: ../../../styles.css
    pdf_document: default
  word_document:
    toc: yes
---

## Context

#### Business intelligence and data-driven decision making

The business will have a better understanding of the complex variety of factors that influence flight departures and cancellations.

The analysis provides visualisations to help summarise and communicate the story provided by the data, as well as a regression model to assist in explaining the various factors associated with departure delays and cancellations. 

The analysis allows the business to make data driven decisions based on the key findings presented and suggests further areas for exploration to help provide a better understanding of underlying factors causing flight delays. 


#### Domain knowledge and the business context

The analysed data comes from Newark Airport, based in New Jersey, USA. Although in New Jersey, Newark services the New York City area along with JFK and LaGuardia airports (both based in New York City).

The analysis looks at the domestic flight departures from Newark throughout the year 2017. The business would like to better understand the impact that weather factors have on delays and cancellations. They also look to gain a better understanding of other factors that may have an impact on scheduled flights. 

The aim of this analysis is to provide key insights that will allow the business to make informed decisions as to the best way to reduce flight delays and cancellations. 


## Data

#### Internal and external data sources

Five datasets were provided by Newark airport:

- flights (30,3748 observations of 19 variables): information on all domestic departure flights from Newark, JFK and LaGuardia across 2017, including scheduled and actual departure times 
- airlines (12 observations on 2 variables): the carrier codes and full names of airline carriers
- planes (3521 observations of 9 variables): meta data detailing further information for models of planes 
- weather (26,201 observations of 15 variables): hourly weather information for Newark, JFK and LaGuardia airports throughout 2017
- airports: this dataset was provided by Newark and contains information on the locations, codes and timezones for airports in the USA. *The airports dataset was provided but not used for the purposes of the analysis.*

External data:

- additional weather information (365 observations of 4 variables): as the weather information provided by the airport contained a high number of missing values, further information was sourced from meteostat.com to allow a more complete picture of weather conditions at Newark throughout the year. 
Source: https://meteostat.net/en/station/72502?t=2017-01-01/2017-12-31

Data verification:

- Finally, cross checking of data was done by exploring the US Dept of Transportation: Bureau of Transportation Statistics (https://www.transtats.bts.gov/). This helped ascertain that the flight dataset was complete and that flight values with no listed departure time were in fact cancelled flights. 

#### Types of data

The data types used:

  - Numerical, e.g. day, dep_delay, wind_dir
  - Oridinal, e.g month, weekday, visibility
  - Date time, e.g. time_hour, date
  - Character, e.g. origin, model

#### Data formats

All data provided by the airport and downloaded from the meteostat website was in the form .csv.

#### Data quality and bias

The flight, airline, airport and carrier data was all of high quality and in a cleaned and structured format.

Weather data had a high number of missing values for several variables which required further data to be sourced. 

As noted above, cross checking of data was carried out to ensure it's completeness. 

The data is factual and does not contain any opinion or personal identifying information and therefore unlikely to present any bias issues.

The data contained information on domestic departures only, information on all departing flights, including international and cargo could help provide a more holistic understand of the reasons for flight delays and cancellations.  

## Ethics

#### Ethical issues in data sourcing and extraction

As noted, all data is factual and does not contain any opinion or personal identifying information.

There are no foreseen ethical issues with this data.


#### Ethical implications of business requirements

The purpose of the data analysis is to help the business make data driven decisions to help reduce the number of flights delays, therefore allowing them to provide a better experience for air passengers. There is little scope for ethical implications.

Data does include information on airline carriers and their performance can be assessed from the findings. Although this is very low risk in terms of ethical considerations, it could potentially be harmful to those carriers who are not performing competitively, should the business opt in some way to penalise these carriers. 


## Analysis

#### Stages in the data analysis process

The main stages of the data analysis process were:

  - reviewing and understanding the project brief and the business questions being asked, including some pre-planning to increase domain knowledge
  - creating a plan for approaching and breaking down the task at hand 
  - cleaning data and creating R script
  - exploratory data analysis
  - ggplot2 visualisations created
  - further data cleaning for glmulti model building
  - model building and analysis of findings
  - presentation preparation, including findings, conclusion and recommendations

#### Tools for data analysis

All analysis was written in R code using RStudio.

A variety of R packages were used, including:

  - tidyverse
  - janitor
  - lubridate
  - glmulti
  - patchwork
  - GGally
  - pROC
  - modelr

Microsoft powerpoint was used for the final presentation.

GitHub was used to store data and version history.

#### Descriptive, diagnostic, predictive and prescriptive analysis

The analysis carried out is both descriptive and diagnostic. 

The descriptive analysis tells you explains when flights ehave been delayed and under what circumstances. The diagnostic analysis explains the particular factors that impacted/caused flight delays or cancellations.

# PDA Outcomes

### Working with Data (J4Y6 35)

#### 1. Plan an analysis to provide business intelligence

-   1.1 Business intelligence and data-driven decision making
-   1.2 Domain knowledge and the business context
-   1.4 Internal and external data sources
-   1.5 Data quality
-   1.6 Stages in the data analysis process
-   1.7 Descriptive, diagnostic, predictive and prescriptive analysis
-   1.9 Ethical implications of business requirements
-   1.10 Tools for data analysis

#### 2. Extract data from a variety of sources

-   2.1 Tools for querying data sources
-   2.2 Types of data (categorical and numerical data and their sub-types)
-   2.3 Data formats
-   2.6 Data quality including data bias
-   2.7 Ethical issues in data sourcing and extraction

#### 4. Analyse data to provide business intelligence

-   4.7 Role of domain knowledge in interpreting analyses
